info:
  name: mybatisPlusDemo
  contact: mybatisInterceptorDemo

server:
  port: 8800

Spring:
  datasource:
    schema: classpath:userDo.sql;
#    data: classpath:data-h2.sql  插入表数据的sql
#
##mybatis plus
mybatis-plus:
  #支持通配符*或者;分割-------只对注解方式的枚举处理能提前加载缓存.
  type-enums-package: com.zy.mybatisplusdemo.core.enumerate

  mapper-locations: classpath*:mybatis-plus-mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  aliasesPackage: com.zy.mybatisplusdemo.dao.model
  #扫描mapper文件包名
  type-aliases-package: com.zy.mybatisplusdemo.dao.mapper
  global-config:
    #自定义填充策略接口实现【这里定义的handler并不能生效，目前还不知道为什么，需要手动设置gloableConfig到MybatissqlSession中才行】
    #    meta-object-handler: com.zy.mybatisplusdemo.core.config.MetaObjectHandlerConfig
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: AUTO
      #      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      #      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1 #逻辑已删除（默认值1）
      logic-not-delete-value: 0  #逻辑未删除（默认值0）
      db-type: mysql
    refresh: true

  #自定义SQL注入器
  #sql-injector: com.baomidou.mybatisplus.extension.injector.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler


#log_config
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.zy.mybatisplusdemo: debug
    org.springframework.boot: info
