info:
  name: mybatisPlusDemo
  contact: mybatisInterceptorDemo

server:
  port: 8800

spring:
  data:
    mongodb:
      database: mongdb_test
      host: 127.0.0.1
      port: 27017


#log_config
logging:
  config: classpath:logback-spring.xml
  level:
    root: info
    com.zy.mybatisplusdemo: debug
    org.springframework.boot: info

